### ISSUE TITLE
Enhancements?

### ISSUE THREAD

**Issue by sdwfrost** [emvolz/treedater#1]
Hi @emvolz 

Some suggested minor tweaks:

- Add in a field for the elapsed time (handy for benchmarking) and number of iterations
- Include an option for 'quiet' during optimisation
- Add in a field for the TMRCA (I assume it's `min(x$Ti)` though)

**Comment by emvolz** [comment]
I have added a 'quiet' option. Also timeToMRCA and timeOfMRCA in return value.
