### ISSUE TITLE
Missing dates

### ISSUE THREAD

**Issue by slvrshot** [emvolz/treedater#14]
Hi again I was able to load in my tree and the metadata. I created a data frame corresponding to the dates, and that loaded perfectly. However, after running the following commands I recieved an error that I am missing sample time information. What should I do about samples in the tree for which I have no dates? Additionally for the mrl values are these just guides or do I need to change this respective to my bug?

```
tre <- ape::read.tree

tre <- read.tree("RAxML_bipartitionsBranchLabels.finalTree")
tre <- unroot(tre) # will estimate root position

#Load Metadata: 

md <- read.csv( 'Isolate_Metadata.csv', sep = ',', header = TRUE )
rownames(md) <- md$node
head( md )
sts <- md$year
head(sts)
sts.df <- data.frame(lower = sts[1:2] - 0, upper = sts[1:2] + 1 )
head(sts.df)
```
```
mrl <- c( .0005, .002 ) # the estimated clock rate should fall between these values 
s.dtr0 <- dater( tre, sts, s = 18e3 , estimateSampleTimes = sts.df , quiet = FALSE, ncpu = 6, strict=TRUE, meanRateLimits = mrl)

Error in dater(tre, sts, s = 18000, estimateSampleTimes = sts.df, quiet = FALSE,  : 
  Missing sample time information.
```

Thanks for your help!

**Comment by emvolz** [comment]
Hi. The error suggests that there is at least one sample in the tree that is not mentioned in the 'sts' vector OR the 'sts.df' data frame. Also make sure row names on 'sts.df' correspond to tree tip labels. 

To find the culprit, try this: 
```
setdiff( tre$tip.label, names(sts ))
setdiff( tre$tip.label, rownames( sts.df )) 
```

Regarding 'mean rate limits', these are optional, but if there is not a strong temporal signal in your data set you can use this to constrain the rate to a realistic range.

**Comment by emvolz** [comment]
Further to my last comment, the dater function actually should have printed out the names of samples missing date information: https://github.com/emvolz/treedater/blob/4d4c2dc8deaf2bbdd2e7a9a3400aa878dd43e01c/R/treedater0.R#L660

Did it not print this out?

**Comment by slvrshot** [comment]
> setdiff( tre$tip.label, names(sts ))
> setdiff( tre$tip.label, rownames( sts.df ))



> Further to my last comment, the dater function actually should have printed out the names of samples missing date information:
> 
> https://github.com/emvolz/treedater/blob/4d4c2dc8deaf2bbdd2e7a9a3400aa878dd43e01c/R/treedater0.R#L660
> 
> Did it not print this out?

I am going to check my files and see what happened. No it did not print that out. I'll get back to you shortly. Thanks again!

**Comment by slvrshot** [comment]
@emvolz 

Hi again Erik - first I realized my original metadata data frame did not contain all of the tip labels of the input tree. I fixed this. I also realized the sts.df data frame was not looking at all 840 samples so I altered my code to this:

[sts.df <- data.frame(lower = sts[1:840] - 0, upper = sts[1:840] + 1 )](url)

I am however not sure how to have the [sts.df](url) correspond to the tip labels. Would you be able to assist?

**Comment by emvolz** [comment]
I would check the contents of `sts.df` carefully...The error message suggests there are NAs, which may have been inherited from the `sts` vector. Regarding samples without any bounds: Yes - the safest course is to remove them, however you could also give them very wide bounds in `sts.df`

**Comment by slvrshot** [comment]
Would you mind if I sent some example files to your email?

**Comment by emvolz** [comment]
Not at all: erik.volz@gmail.com
I will close the issue for now, but will re-open if I discover a bug
