### ISSUE TITLE
Units for meanRateLimits 

### ISSUE THREAD

**Issue by ksw9** [emvolz/treedater#17]
Hi, 

Thanks for a great program. I'd just like to confirm that I'm correctly understanding the units in the dater function. omgeg0 should be in units of substituions/site and so should meanRateLimits, correct? Does the seqlen parameter include the full length of the genome, if an ML tree was inferred from a SNPs called from the full genome (with ascertainment bias correction for invariant sites)? 

Thank you and best,

**Comment by emvolz** [comment]
Hi - The units are substitutions / site / unit time (usually years, depends on units in your sample time vector).
Yes- Units are same for the omega0 and meanRateLimits parameters. 
The sequence length should match the data used to estimate the tree, so if you are using SNPs you would want to use the number of SNPs. Usually results aren't too sensitive to this and you can use the approximate number. Note you will estimate a higher clock rate for a tree based on SNPs than you would for whole-genome data.

**Comment by ksw9** [comment]
Great - thank you for the clarification!
