### ISSUE TITLE
sts

### ISSUE THREAD

**Issue by lixingguang** [emvolz/treedater#3]
I have a csv file that contained the sampling time, the first column is the sequence name, and the second column is the sampling time, how can I transform it into the "sts" for treedater, thanks.

**Comment by emvolz** [comment]
There are many ways this could be done, so I would read up on basic input/output for R. 
The basic procedure would be something like 
1) df = read.csv(...) to load a data frame with the sample times
2) sampleTimes = df[, <column name>] 
3) names( sampleTimes )  df[, <other column name>]
